spring.application.name=usuarios

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/usuarios_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=5b8c34f8a7d2e901f4c6b1a3d8e5f7a2b9c0d1e4f6a8b3c5d7e9f1a2b4c6d8e0
jwt.expiration=86400000